### PR TITLE
update pt_BR localization: translate new strings

### PR DESCRIPTION
**Pull request by augusto-herrmann**
This PR makes the Brazilian Portuguese localization up to date with the English defined strings.

### CODE REVIEW

**Comment by augusto-herrmann** [comment]
Care to review, @gaugsouza ?

**Comment by augusto-herrmann** [comment]
Ping @gaugsouza.

@JustinBack do we have another person that could also review this?

**Comment by JustinBack** [comment]
Sorry for the late reply, I'll merge it :-)

**Comment by augusto-herrmann** [comment]
Thanks, @JustinBack!

**Pull request merged**
